### PR TITLE
MTV Support

### PR DESCRIPTION
**Pull request by SavageCore**

### CODE REVIEW

**Comment by jimrollenhagen** [comment]
Oops, this conflicts with the FL fix for user scripts. Mind a rebase? :)

**Comment by SavageCore** [comment]
This looks good to go now, messed up notwhat so I'll re pull that shortly...

**Comment by SavageCore** [comment]
@jimrollenhagen bump

**Comment by jimrollenhagen** [comment]
Sorry for the delay! Thanks @SavageCore :)

**Pull request merged**
