### PR TITLE
add example conf files

### PR DESCRIPTION
**Pull request by gnowxilef**
create example conf files and update instructions on how to set up pywhatauto

### CODE REVIEW

**Comment by gnowxilef** [comment]
poke?

**Comment by SavageCore** [comment]
This seems dead for now... Mind doing a PR on my [fork](https://github.com/SavageCore/pywhatauto)?

**Comment by gnowxilef** [comment]
are you the main maintainer of pywhatauto now? just curious/

**Comment by SavageCore** [comment]
Nope, just a guy who still uses it for download button and maintaining that side of things but I welcome everyone to chip in to it until jimrollenhagen surfaces. I know he is on PTH and going to work on Sherlock again.

**Comment by jimrollenhagen** [comment]
This has conflicts now, mind rebasing? :(

**Comment by gnowxilef** [comment]
done.

**Comment by jimrollenhagen** [comment]
Sorry, I did it again :( I can rebase if you like.

We also shouldn't move regex.conf, that's not really meant to be edited by users. We might be able to rename it, since the auto-update mechanism doesn't work right now.

Otherwise LGTM.

**Comment by gnowxilef** [comment]
please do.

**Comment by jimrollenhagen** [comment]
Okay, I've rebased, touched this up, and merged it. Thanks for the PR! :)

**Pull request closed without merging**
